### PR TITLE
Fix #2991

### LINKED ISSUE #2991: Empty @media queries generated when compiling less file with (reference) to bootstrap
This bug was originally reported to WebCompiler but was stated to be a bug with the node-less module. Please refer to original bug report for more information:

https://github.com/madskristensen/WebCompiler/issues/269

### Installed product versions
- Visual Studio: 2015 Professional
- Web Compiler extension: 1.11.319
- Bootstrap less 3.3.7

### Description
Empty @media queries generated when compiling less file with (reference) to bootstrap 

### Steps to recreate
1. Download bootstrap less files from http://getbootstrap.com/getting-started/#download
2. Create a less file with a reference import to bootstrap.less and use a mixin:
image

3. Compile your less file

### Current behavior
The css file contains many empty @media queries
image

### Expected behavior
The css file should not contain empty @media queries
`.mybutton {
  padding: 1px 1px;
  font-size: 1px;
  line-height: 1px;
  border-radius: 1px;
}`

### PR DESCRIPTION
**Pull request by MoonCoral**
Closes  #2991

Only comments have `isSilent` as far as I could see. No comment should cause a parent to be printed in the 'referenced' case.
Thus I'm not even sure what the condition I deleted aimed to achieve.

Test is based on the snipped posted in #2991. `css-3.css` contained an empty `@` rule, I assume to bypass the issue raised in #2991.

### CODE REVIEW

**Comment by MoonCoral** [comment]
Test failure seems to be a change of formatting of an error message in node 16. I don't see any relation to my changes.

```
 - /home/runner/work/less.js/less.js/packages/test-data/errors/eval/javascript-error: FAIL
SyntaxError: JavaScript evaluation error: 'TypeError: Cannot read property 'toJS' of undefined' in /home/runner/work/less.js/less.js/packages/test-data/errors/eval/javascript-error.less on line 2, column 10:¶
SyntaxError: JavaScript evaluation error: 'TypeError: Cannot read properties of undefined (reading 'toJS')' in /home/runner/work/less.js/less.js/packages/test-data/errors/eval/javascript-error.less on line 2, column 10:¶
1 .scope {
2     var: `this.foo.toJS`;
3 }
```

**Comment by iChenLei** [comment]
@MoonCoral Yes, it's not your issue.
@matthew-dean  Hi, Matthew. What't your opinion about this CI failure case ?

**Comment by iChenLei** [comment]
@MoonCoral  CI has been fixed, please update your work, thanks !

**Comment by matthew-dean** [comment]
If all other tests pass, this seems good.

**Review by matthew-dean — APPROVED** [review]

**Pull request merged**
