### PR TITLE
Plugins: If minVersion >= 3.0.0, don't "pre-run" .setOptions()

### PR DESCRIPTION
**Pull request by calvinjuarez**
This is just what I was mentioning in https://github.com/less/less.js/issues/3233.  Turned out to be simple enough.  Tests were updated and a 3.x test was added.  If no `minVersion` is specified by a plugin, `setOptions()` is run twice to be safe.  Maybe no specification should "assume v3+"?  That could break more old plugins created without the `minVersion` property.

### CODE REVIEW

**Comment by matthew-dean** [comment]
@calvinjuarez I really like this. Much cleaner. Maybe remove `.editorconfig`? (I realize I made the opposite argument for the `.vscode` file, but that file was for launching tests, whereas this is config?)

Also, CI tests are failing?

**Comment by calvinjuarez** [comment]
_.editorconfig_ is meant to be a way to share and enforce coding standards across editors.  I can keep it out, but I think it has value in the repository.  (See https://editorconfig.org).  I don’t mind ignoring it, if it’s not seen as generally useful, but it’s a nice way for me to contribute using my preferred IDE and others to use theirs without having to manually change editor settings (I use tab indentation on my work and personal stuff, for example).

As for the CI failures, I wondered about that.  I’m not hip to CI, so I could use some help knowing how to review what’s broken so I can fix it.

**Comment by calvinjuarez** [comment]
Okay, I think I see what the tests are verifying.  I’ll try to test on all version soon of Node in the tests.  Stay tuned.

**Comment by matthew-dean** [comment]
@calvinjuarez The error is the same as on main. Which is: `SyntaxError: setOptions() not called before install`. 

It seems like there's some race condition around setting options and install? Somewhere there must be an async callback. So you didn't cause this, but since you're looking at set options, do you think you could track it down? It doesn't happen every time, and console logging causes it to stop happening, I think? (Because it's slowing down the race.)

**Comment by matthew-dean** [comment]
Please merge again from master and it should work. [crosses fingers]

**Pull request merged**
