### PR TITLE
Use eslint out of Grunt. Added script to lint js.

### PR DESCRIPTION
**Pull request by anthony-redFox**
grunt has strict dependency on eslint version and too hard to upgrade new version

### CODE REVIEW

**Comment by matthew-dean** [comment]
@anthony-redFox Is the Appveyor failure here the one that was fixed with your other PR? And other that that this is mostly an ESLint bump with ESLint fixes?

**Comment by matthew-dean** [comment]
Closed and opened to trigger rebuild.

**Comment by matthew-dean** [comment]
@anthony-redFox Side note, you've had a few PRs cleaning up some of the core dependencies and scripts. Might you be interested in joining the core less team and taking on repo maintenance? See: https://github.com/less/less.js/issues/3148

**Comment by anthony-redFox** [comment]
@matthew-dean  open source just my hobby. and yes will be nice to working with project but when I have time (as you know everyone have a job and family which have more priority than other things). 

@matthew-dean  or @seven-phases-max can you take a look.

**Pull request closed without merging**
