### PR TITLE
Unescape escaped strings

### PR DESCRIPTION
**Pull request by ricardobeat**
Attempt at fixing #1142. Not sure this belongs in the parser or `tree.Quoted`.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@ricardobeat, is this still relevant?

**Comment by seven-phases-max** [comment]
Hmm, I actually wonder how this can be fixed at all. Currently Less not process `\` at all to leave it for browsers. But if Less start to process CSS escaping then it wil break certain (not all) CSS hack, e.g. `blue\9`. In oteher words the problem is that it's impossible to guess a user intention (if it escapes for Less or for the resulting CSS).

So I wonder if this (and all related) issues/PRs should be closed. (and `'"`'`, `"'"` things be suggested as solutions).

**Comment by matthew-dean** [comment]
Escapes should be left as is, because they're valid in all identifiers and strings. You can escape any special character, regardless if it NEEDS escaping, as a matter of personal style. It has nothing to do with hacks. So no, you can't unescape escapes. I suggest closing.

**Comment by matthew-dean** [comment]
In other words, IIRC, ```.blue\9 { }``` is the equivalent of ```.blue9 { } ``` but ```.\9blue { }``` is not the equivalent of ```.9blue { }```, so if you started unescaping, you'd have to have a lot of logic to handle where the escaping happened and what the content of the escape was.

**Comment by seven-phases-max** [comment]
Closing per decision above (After all it's been several years with no real-world issues reported for current behaviour).

**Pull request closed without merging**
