### PR TITLE
Make sourcemap generation a bit faster

### PR DESCRIPTION
**Pull request by nicks**
see #2828

### CODE REVIEW

**Comment by nicks** [comment]
This basically memoizes the split() call. That way, we split the lines once per file instead of on every mapping. And it provides a class to add future memoization.

**Comment by nicks** [comment]
hi, is this pull-request OK?

**Comment by matthew-dean** [comment]
Looks good to me. Pulling. Thanks!

**Comment by matthew-dean** [comment]
Note that this PR needed to be reverted. You're welcome to open a new PR, but because the first PR passed Less tests, you would need to add tests demonstrating the first PR failing, and the second PR succeeding.

See: https://github.com/less/less.js/issues/2896

**Comment by frostyfrog** [comment]
Might want to reopen #2828? :wink:

**Comment by matthew-dean** [comment]
@frostyfrog Good catch, thanks!

**Pull request merged**
