### PR TITLE
Release v4.1.3

### PR DESCRIPTION
**Pull request by matthew-dean**

### CODE REVIEW

**Comment by iChenLei** [comment]
@matthew-dean e2e tests with puppeteer and some tests encount timeout limit, these tests is not stable, need time to figure out how to improve stableness.

**Review by iChenLei — APPROVED** [review]

**Comment by iChenLei** [comment]
@matthew-dean  Hi, sir. It's time to relase v4.1.3, thanks!
@joeyparrish Thanks for your reminder.

**Comment by matthew-dean** [comment]
Sorry! Tried publishing today. Getting an `E404` 

> Not Found - PUT https://registry.npmjs.org/less - Not found
> npm ERR! 404 
> npm ERR! 404  'less@4.1.3' is not in the npm registry.

Maybe haven't set up something correctly here hmm

**Comment by matthew-dean** [comment]
Ah, I had to do `npm login` on this new macbook. Published!

**Comment by iChenLei** [comment]
@matthew-dean  Thank you, Sir ! And can you add changelog to [github release](https://github.com/less/less.js/releases) and [changelog.md](https://github.com/less/less.js/blob/master/CHANGELOG.md) ?

**Pull request merged**
