### PR TITLE
Fix for #2812 and #2844 

### PR DESCRIPTION
**Pull request by arapoport**
Hi, I fixed both issues. I tested them locally and I also run standard test. Seems to be OK. I am not sure how to write automatic tests, especially for #2844 which happens randomly and depends on browser communication...

### CODE REVIEW

**Comment by matthew-dean** [comment]
Thanks so much! I meant to get to this earlier and didn't have time. I'll test this out (again, hopefully soon lol).

**Comment by matthew-dean** [comment]
Btw, what about adding a browser test for this case? Do you think you could do that?

**Comment by matthew-dean** [comment]
Currently this PR is generating an error in Less tests
```
Running "jasmine:production" (jasmine) task
Testing jasmine specs via PhantomJS

 less.js production behaviour
   X doesn't log any messages
```
Meaning, something is generating logs when it shouldn't.

**Comment by arapoport** [comment]
Indeed, you are right. I added a log output for the case when no sheets are loaded. Before in this situation promise would not be resolved at all and no log was written... Maybe the test case should be changed. Or maybe it is dangerous to start now resolving the promise in every situation...

**Comment by arapoport** [comment]
BTW, the log call that causes that problem is less.logger.info() call. Which shouldn't appear in production anyway... I am not sure where the problem lies.

**Comment by matthew-dean** [comment]
@arapoport Well I think that it's correct to have a Promise always reject or resolve. Especially since the rest of the code is written to expect it. I'll see if something different should happen with those logging lines.

**Pull request merged**
