### PR TITLE
update source_map to 0.6.x 

### PR DESCRIPTION
**Pull request by akkumar**
#3179 typescript definitions of source_map are available as part of source-map package from 0.6.0 . 
Needed by downstream projects. hence upgrading source_map to 0.6.x

### CODE REVIEW

**Comment by matthew-dean** [comment]
Thanks!

**Comment by akkumar** [comment]
Great thanks. @matthew-dean . I assume this is now part of 3.0.4 release ? 

(Given the nature of change - I was wondering if bumping up the minor version to 3.1.0 might be appropriate ? )

Also independently, happened to look at - https://github.com/less/less.js/blob/master/CHANGELOG.md , and https://github.com/less/less.js/releases , it does not seem to contain the changelog of the recent releases , 3.0.4 - say. Would it be possible to capture the same for reference purposes ?

**Comment by matthew-dean** [comment]
> Given the nature of change

@akkumar Can you elaborate? You mean because it's not so much a bug fix but a feature bump? Maybe, technically, yes. 

I probably won't have time to do an update for the Changelog. You're welcome to submit a PR for it.

**Comment by akkumar** [comment]
> You mean because it's not so much a bug fix but a feature bump? 


So source map 0.6.x+  (this patch) does enforce node compatibility of node 6+ . Something not expected of a minor release version usually.

**Comment by akkumar** [comment]
>  You're welcome to submit a PR for it.

#3207 added for the same , capturing this change at the minimum

**Comment by matthew-dean** [comment]
> So source map 0.6.x+ (this patch) does enforce node compatibility of node 6+ 

Oh. That wasn't clear from this PR, unfortunately. I thought it was adding Node support, not adding a minimum Node version requirement.  :/

**Pull request merged**
