### PR TITLE
feat: add support for case-insensitive attribute selectors

### PR DESCRIPTION
**Pull request by iChenLei**
**What**:

add support for case-insensitive attribute selectors
try to fix https://github.com/less/less.js/issues/3027 https://github.com/less/less.js/issues/3670 https://github.com/go-gitea/gitea/pull/15520 https://github.com/go-gitea/gitea/issues/15565

**Why**:

CSS spec -> https://www.w3.org/TR/selectors-4/#attribute-case

**How**:

https://github.com/less/less.js/issues/3027#issuecomment-828223873

**Checklist**:

- [ ] Documentation
- [x] Added/updated unit tests
- [x] Code complete

cc @matthew-dean

### CODE REVIEW

**Comment by matthew-dean** [comment]
Looks great! Thanks so much! One thing I'm thinking of -- IIRC, I believe there are tests somewhere that test attribute equality. Essentially there are tests like:
```less
.foo where ([attr=value] = [attr="value"]) { }
```
So we may want to add this attribute selector to the equality check as well.

**Comment by iChenLei** [comment]
@matthew-dean Thanks for review, will add more unit test later. 😄

**Comment by iChenLei** [comment]
@matthew-dean Sir, looks like current not support use `when` to compare attrbuite selectors(without case-insensitive flag) ?

**Comment by matthew-dean** [comment]
@iChenLei Oh, no? Then never mind! Thanks for checking it out!

**Review by matthew-dean — APPROVED** [review]

**Comment by iChenLei** [comment]
@matthew-dean puppeteer e2e test often fail. 😢  https://github.com/less/less.js/runs/4619921788?check_suite_focus=true

**Pull request merged**
