### PR TITLE
replace deprecated Buffer constructor (#3305)

### PR DESCRIPTION
**Pull request by gabrielschulhof**

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
Fixes https://github.com/less/less.js/issues/3305

**Comment by matthew-dean** [comment]
Wait..... how is `dist/less.js` affected / changed? That should be auto-generated from `grunt dist`. What is creating that Buffer in the browser version?

I don't see any dependency changes, so this PR doesn't make sense how that dist file is being generated.

**Comment by matthew-dean** [comment]
Oh, I see.... it's being added by Browserify, but why....... 🤔

**Comment by gabrielschulhof** [comment]
@matthew-dean I have now updated the PR.

**Pull request merged**
