### PR TITLE
ES6 & rollup #2691

### PR DESCRIPTION
**Pull request by glixlur**

### CODE REVIEW

**Comment by matthew-dean** [comment]
It looks like this PR has both module dependency and ESLint errors. See: https://ci.appveyor.com/project/lukeapage/less-js/build/846/job/yirx7i25rilt1x13. Can you clean it up?

**Comment by alexlur** [comment]
Fixed

**Comment by matthew-dean** [comment]
@glixlur There are still errors. The CI environments run `grunt shell:test` if you want to verify it's working before pushing.

**Comment by matthew-dean** [comment]
?

**Comment by glixlur** [comment]
Sorry, I don’t have enough time for this.

**Pull request closed without merging**
