### PR TITLE
Bubbling of nested directives

### PR DESCRIPTION
**Pull request by SomMeri**
Related to #1691 and #2104 

Directives are changed to work the same way as media. The biggest code change is that the `rules` property of `directive.js` contains an array instead of just a ruleset. 

Directive bubbling ends at the closest directive or media, e.g. this remains unchaged by compilation:
````
@media print {
    @supports (upper: test) {
        @supports not (-webkit-font-smoothing: subpixel-antialiased) {
           @media screen {
              nested {
                property: value;
              }
           }
        }
    }
}
````

### CODE REVIEW

**Comment by SomMeri** [comment]
Travis is failing, but other less.js pull requests are failing on the [same error](https://travis-ci.org/less/less.js/jobs/51860624).

**Comment by lukeapage** [comment]
Please could you merge latest? then builds should pass...

**Comment by lukeapage** [comment]
great work though, thanks, will be a nice feature

**Comment by SomMeri** [comment]
I merged it and build is passing. You are welcome ;)

**Pull request merged**
