### PR TITLE
Master

### PR DESCRIPTION
**Pull request by SabirPerek**
Undefined source map should result in an empty map file.

### CODE REVIEW

**Comment by seven-phases-max** [comment]
@SabirPerek  
Could you elaborate please. What actually this PR is about, and why does it go to a separate branch?

**Comment by seven-phases-max** [comment]
I suppose you're juts testing GitHub features, so I'm closing this as irrelevant.

**Comment by SabirPerek** [comment]
Hey yea sorry I was just trying to get familiar with github and was testing
it out. Sorry if I messed something up. I was assuming that I only made
changes on my local machine and that it wouldn't affect anything.

**Comment by seven-phases-max** [comment]
No problemo.

**Pull request closed without merging**
