### PR TITLE
Type checking length units

### PR DESCRIPTION
**Pull request by jacobwarduk**
Resolves issue: #3023 Incorrect type-checking for CSS length units

### CODE REVIEW

**Comment by seven-phases-max** [comment]
#2326 ?

**Comment by jacobwarduk** [comment]
@seven-phases-max please read issue #3023, which this PR resolves.

**Comment by seven-phases-max** [comment]
#3023 is OK (see complete LU list below though), but could you please annihilate the`is` festival?

https://www.w3.org/TR/css-values-3:
```css
em, ex, ch, rem, cm, mm, q, in, pt, pc, px, vw, vh, vmin, vmax
```

**Comment by jacobwarduk** [comment]
@seven-phases-max sorry, I understand what you mean now. 

Please excuse my sleepy head late last night 😴

I'll refactor it to use `isunit` rather than introducing a load of `isfoo`/`isbar`/`isbaz` type methods later today. And yes, you're correct, the should really be case insensitive.

**Comment by jacobwarduk** [comment]
- [ ] Use `isunit` instead of the `isFoo` festival.
- [ ] Add case-insensitivity to unit matcher.
- [ ] Add all units from the complete LU list.

**Comment by jacobwarduk** [comment]
@seven-phases-max I have resolved your comments and updated my PR :)

**Comment by seven-phases-max** [comment]
Thanks!

**Comment by matthew-dean** [comment]
Thanks! I'll try to tag and push a release soon on NPM.

**Pull request merged**
